spring.application.name=backend

# Duomenų bazės adresas (XAMPP MySQL standartinis portas yra 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/dms?serverTimezone=UTC
spring.datasource.username=root
# XAMPP pagal nutylėjimą slaptažodžio neturi, tad palik tuščią
spring.datasource.password=Ananasas.1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate nustatymai (automatiškai sukurs lenteles pagal tavo Java klases)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Storage settings
dms.storage.templates=./storage/templates
dms.storage.generated=./storage/generated